[package]
name = "LingStone"
version = "0.0.1"
edition = "2024.beta"
published-at = "0xc5128ab446ccd272f15db6d21f718ff4c2811019ade9dd00a77c6c2cf4c35bb4"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
lingstone = "0x0"
taixu = "0x0"
std = "0x1"
